apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: at-app2
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: aks-backup-poc
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "P@ssw0rd123!"
